version: 2

sources:
  - name: ecommerce
    database: synthetic-ecommerce
    schema: ecommerce_analytics
    tables:
      - name: raw_page_view
      - name: raw_add_to_cart
      - name: raw_purchase
      - name: raw_ad_click